### ISSUE TITLE
Dear author, hello, the runtime is stuck at this location

### ISSUE THREAD

**Issue by mr00ff** [balopez83/macOS_On_Hyper-V#14]
cpu: intel
![hy](https://github.com/balopez83/macOS_On_Hyper-V/assets/48547769/65e40eee-de71-400d-86e6-08c20bd03482)

**Comment by balopez83** [comment]
@mr00ff  I Need a lot more information. What are you trying to do? Is this the verbose from the installer or an already installed OS? What OS version is this? Did you make any modifications to the config.plist or any of the files in the EFI folder? If you made a modification did you use anything other than ProperTree to make the edits?

Unfortunately there is too little information in that verbose screenshot to provide an answer without the above questions answered though I would suspect there is something that was edited in your config.plist that shouldn't have been or an issue with how you created your virtual machine where a setting may be wrong.

**Comment by balopez83** [comment]
@mr00ff After a quick google search I suspect you are booting the web installer but did not configure your internet settings correctly per the instructions? Please check that your hyper-v vm is configured exactly as described in the instructions.

**Comment by mr00ff** [comment]
> @mr00ff 经过快速的谷歌搜索，我怀疑您正在启动 Web 安装程序，但没有按照说明正确配置您的互联网设置？请检查 hyper-v vm 的配置是否完全按照说明中所述进行。

I followed the installation instructions to set up super v, which got stuck here after turning on the virtual machine. After several subsequent resets, I was able to install the system normally, but it got stuck in the last minute. After waiting for a few hours, the system still couldn't be successfully installed I have not modified any configuration or files in config.json

**Comment by balopez83** [comment]
@mr00ff what is the OS version you are installing? What amount of memory did you give the virtual machine and what intel CPU model/generation is the host machine.

**Comment by balopez83** [comment]
@mr00ff Added a new release that may resolve the issue experienced. Not sure if it will fix it but wanted to get a fix out there quickly due to all the issues people have had with the previous release. Please let me know if this resolves your issues.
