### ISSUE TITLE
Can't not boot on Intel i5 13420h laptop cpu

### ISSUE THREAD

**Issue by Drnfrf** [balopez83/macOS_On_Hyper-V#15]
Hi developer  , I am unable to boot the macos recovery from Intel 13th gen cpu

**Comment by balopez83** [comment]
@Drnfrf Please provide additional information. What version of macOS are you trying to install? What amount of memory did you assign to your Hyper-V virtual machine? Can you provide a screenshot of the verbose output of the booting virtual machine?

**Comment by Drnfrf** [comment]
[EFI - CPU spoof for never CPUs.zip](https://github.com/balopez83/macOS_On_Hyper-V/files/13483960/EFI.-.CPU.spoof.for.never.CPUs.zip)
 hi developer i was trying to run the default with catalina recovry dmg but it didnt work so i switched the uefi with this and i was getting apple logo but it still didnt work , so i changed the recovery with this https://drive.google.com/file/d/1MNLVPNuzbjZJIy9vlEZD3tjSE37dJyTq/view and i am somewhat close 
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/152216552/f6a9e864-d630-4c1f-99e6-bf59d12ba5e1)

**Comment by balopez83** [comment]
@Drnfrf I am glad you are closer though it really should have installed Catalina with the release EFI on the repo with your CPU. By default I have the CPU spoofed correctly to allow Intel Gen 11 and newer Host CPU's to be able to run macOS on Hyper-V. I suspect you might have had a couple Hyper-V VM settings that needed to be changed to get it running. Can you confirm you have at least 8gb of ram assigned to the virtual machine? MacOS does not work properly without at least 8gb of ram assigned to the virtual machine in Hyper-V. I suspect you may be running a patched recovery which may work to install but might have issues later on.

**Comment by Drnfrf** [comment]
Yes I had 8gb of ram assigned and checked uefi and recovery multiple times but it didn't work , at present Mac OS Monterey is successfully installed but Its working slower than VMware , idk why

**Comment by Drnfrf** [comment]
No I think it's same or maybe a bit resposive that VMware at 720 p , how can I make it full screen and assign more vram currently it only has 3 MB vram

**Comment by Drnfrf** [comment]
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/152216552/f151765c-371f-4d16-81bb-b51f90669ec7)

**Comment by balopez83** [comment]
@Drnfrf Hyper-V support for macOS is still in the early stages. Currently there is no way to make it go full screen and there is no graphics acceleration. At this stage if you are looking for a more usable experience virtualizing macOS you would want to use VMware and not Hyper-V.

You can look at the quirks section of my repo for some ways to speed up the virtual machine but overall it still is not usable as a daily use virtual machine. I hope that the developers of OpenCore and many of the key kexts for Hyper-V are able to eventually enable graphics acceleration but it will likely be a long time from now. 

Depending on your machine specs you may want to look at bare metal installation if you are looking for a native experience with graphics acceleration. Keep in mind bare metal installation with graphics acceleration requires an Intel 10th generation or older and some AMD systems.

**Comment by Drnfrf** [comment]
i find hyper v to be the best in responsiveness , i think its better than vmware but only thing im missing is the audio . is there any video editing software for mac that i can use without gpu , ive tried final cut pro trial and davinci

**Comment by balopez83** [comment]
Understand, yes because the screen resolution is smaller by default in Hyper-v things are snappier than with VMWare. 

Audio unfortunately isn't supported yet so to a lack of implementation of the driver stack in Hyper-v from what I've read.

Unfortunately I am not aware of any non-gpu intensive video editing software. You could try open source solutions like Shotcut and OpenShot and see if they have an option to turn off going rendering but I suspect it would greatly slow down processing. Since those solutions work on Windows and Linux you would probably be better off just using them on the host system though.

Also Hyper-v doesn't have a usable usb stack to allow sharing usb devices so the only way to even get video to the Hyper-v would be to download it from the internet or copy to another vhdx drive and then mount that drive as another drive in Hyper-v which is a lot of workarounds unfortunately.

In fact if you're gonna be doing video editing I would highly recommend just getting a cheap 10th gen computer to natively run macOS on bare metal. Microsoft has a surface go 3 i3 refurbished that's super cheap and I know that macOS can be installed on it with touch screen, pen, native wifi and almost everything working. I'm sure there are other computers that might fit your needs better too but for very little you could use the Mac software with full GPU acceleration fairly easily.

**Comment by balopez83** [comment]
Not sure if you have a desktop or laptop but you might be able to use a dGPU or eGPU to get macOS running on your 13th gen computer. You would need to research ones that are still compatible with macOS but that could be an option. I'm not fully familiar with how to do it but a dGPU or eGPU can also be passed directly to vm's allowing for graphics acceleration. You obviously wouldn't be able to use that GPU with windows while doing that but I know it's been done. I don't believe Hyper-v will work like that but I think VMware and Qemu can. In the best example I saw of that someone uses a light headless Linux install that automatically launched a modified qemu vm of macOS with full graphics acceleration and near native speed. Can't help do it but if your feeling adventurous it might be a fun direction to go with it if you want full macOS support on your 13th gen.

**Comment by Drnfrf** [comment]
> Not sure if you have a desktop or laptop but you might be able to use a dGPU or eGPU to get macOS running on your 13th gen computer. You would need to research ones that are still compatible with macOS but that could be an option. I'm not fully familiar with how to do it but a dGPU or eGPU can also be passed directly to vm's allowing for graphics acceleration. You obviously wouldn't be able to use that GPU with windows while doing that but I know it's been done. I don't believe Hyper-v will work like that but I think VMware and Qemu can. In the best example I saw of that someone uses a light headless Linux install that automatically launched a modified qemu vm of macOS with full graphics acceleration and near native speed. Can't help do it but if your feeling adventurous it might be a fun direction to go with it if you want full macOS support on your 13th gen.

Hi , I'm using a laptop and it has dgpu but display output is from Intel irix because of having no mux switch . I wanted to run it bare metal but lack of uefi for laptop notebook is preventing me . I just wanted to check how the software performs in Macos like editing software I'm not actually going to do video editing . How can I get the bare metal macos to run? Should I try with the desktop raptor lake uefi that's available

**Comment by Drnfrf** [comment]
My laptop comes with rtx 4050 laptop GPU , I didn't find any support for rtx 20-40 series card , I guess it's not possible to get the graphics acceleration, if I'm stuck with 720 p res and slower response then I think I'll stick to hyper v and keep an out to see if graphics acceleration is possible . I was able to successfully run macos in Intel 10th gen i31005g1 but it didn't have any wifi support so I had to switch back to windows

**Comment by balopez83** [comment]
@Drnfrf makes sense. I hope that there will be more support for acceleration in the future but fear it may not be here before macOS no longer even supports Intel CPU's. 

As for the 10th gen, all you need to do assuming that you don't have an Intel Wifi card is purchase a mini USB wifi adapter. 
You will want to look at this repo for supported USB adapters and the software to run them: https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter

If your 10th gen has an Intel wifi card all you have to do is use this kext to drive it and the bluetooth directly: https://github.com/OpenIntelWireless/itlwm
https://github.com/OpenIntelWireless/IntelBluetoothFirmware

**Comment by balopez83** [comment]
@Drnfrf Added a new release that may resolve the issue experienced. Not sure if it will fix it but wanted to get a fix out there quickly due to all the issues people have had with the previous release. Please let me know if this resolves your issues.

**Comment by Drnfrf** [comment]
let me check if it works , ill update soon

**Comment by balopez83** [comment]
@Drnfrf Did the latest release resolve the issues?

**Comment by balopez83** [comment]
@Drnfrf Closing this issue due to no response. 

Additional information. Video editing software does require a working GPU implementation. While video editing software might work, it would be exceptionally slow relative to a GPU enabled macOS install.
