### ISSUE TITLE
Unable to get past the beginning.

### ISSUE THREAD

**Issue by Masterspidert** [balopez83/macOS_On_Hyper-V#17]
Hello! I have read the past issue that was similar to this, so I will give you the info you asked them for while providing a screenshot.
I am trying to install macOS on hyper v, and I am currently on the installer and the macOS version I am installing is Catalina (10.15). I have tried multiple vm's, and sometimes I try something new, but no matter what I do, even if I do something new, I have been unable to get past this part. I have followed all of the steps from the beginning with no modifications. If you need anymore information, let me know.

![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/152829683/fe8e7ae7-b645-426f-880b-4affe3254abf)

**Comment by Masterspidert** [comment]
Just saw the other comment. I have given the vm 12gb of ram, it is on gen 2, and I have an amd ryzen 7 5800 cpu with 8 cores (I gave the vm half)

**Comment by balopez83** [comment]
@Masterspidert Thank you for all the information. Unfortunately AMD CPUs are not currently supported for hyper-v yet. I am not entirely sure why but the primary hackintosh developers that developed the kexts required to run macOS on Hyper-v have not yet added that support. Until then the only option you have would be using VMware or virtual box to virtualize macOS on an AMD. Once AMD CPUs are supported you will be able to boot properly.
