### ISSUE TITLE
Ryzen 7950X3D 

### ISSUE THREAD

**Issue by Dastano** [balopez83/macOS_On_Hyper-V#19]
Hey,

does the Ryzen 7590X3D requires a CPU patch?

All I get is the following, when booting up my Hyper-V.

![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/197081/b84cdf52-d2af-48f1-a52d-509aed0f5495)

**Comment by lmorales122001** [comment]
.

**Comment by balopez83** [comment]
Closing currently as there is no way to fix this issue at this time.
