### ISSUE TITLE
UEFI Boot not working w/ SecureBoot? (Windows 11 HyperV)

### ISSUE THREAD

**Issue by ElSrJuez** [balopez83/macOS_On_Hyper-V#27]
Downladed the UEFI vhdx. 
ran the download script. 
copied the com.* folder to the root of the UEFI VHD, 
created the VM gen2, 
added the UEFI VHDX to the VM
customized the boot order to for UEFI VHDX to the top.

**Then:**
I got a blank screen, like no UEFI could be loaded?
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/44654300/b16a2709-63ba-4249-a4a4-35268c9a7f80)

**So, just to test:**
Turned off SecureBoot and i got the loader menu, but now it is stuck here:
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/44654300/e20f1a5d-0dca-4ccc-a7d4-9c680a731c24)

**Comment by balopez83** [comment]
@ElSrJuez Yes secure boot is not supported. The installation instructions specifically state that it must be turned off. The current release does not have Secure Boot capabilities. Since it's a virtual machine, secure boot will add no security benefit.

**Comment by balopez83** [comment]
The error you have indicates you may be using an incompatible computer. What processor are you using?

**Comment by ElSrJuez** [comment]
I just remembered my laptop is Ryzen : /
You're right, thanks.
