### ISSUE TITLE
I would like to ask if anyone has tried to directly connect AMD independent graphics to macos. Will the screen still be stuck?

### ISSUE THREAD

**Issue by hashdogcn** [balopez83/macOS_On_Hyper-V#28]
I would like to ask if anyone has tried to directly connect AMD independent graphics to macos. Will the screen still be stuck?

**Comment by hashdogcn** [comment]
I would like to ask if anyone has tried to directly connect AMD independent graphics to macos. Will the screen still be stuck?

**Comment by balopez83** [comment]
@hashdogcn If you mean an AMD CPU with integrated graphics then it is not supported at all.

If you mean will a separate 2nd graphics card by AMD passed through to the hyper-v work. That's also a no. 

There are projects that have passed through a 2nd graphics card not initialized by the host to a KVM but honestly if your system works to do that then it will work with macOS installed bare metal.

If you have an AMD anything, your best bet is to see if another project has been able to get your machine running bare metal.

AMD support is not at all possible currently as the Acidanthera developers have not built kext support. Without that, nothing will get AMD working unfortunately.
