### ISSUE TITLE
Dont see UEFI option to boot from

### ISSUE THREAD

**Issue by esachs4** [balopez83/macOS_On_Hyper-V#29]
I followed the steps, and when I start the Virtual Machine, I am not seeing UEFI as the first option, like it shows in the video.
Running on Windows Server 2022 Standard

![Screenshot 2024-04-22 092715](https://github.com/balopez83/macOS_On_Hyper-V/assets/142461937/15ff2a3d-f240-44bf-a7b6-0f1e22ca467c)

**Comment by balopez83** [comment]
You are booting the UEFI disc so you won't see it as an option. 

You skipped some steps in section 1 of the installation guide. You did not properly copy over the web installer for macOS. Once that has been done correctly you will have the option in that screenshot.


One additional note. This does not work on server hardware. macOS does not support Xeon, Pentium, Celeron, or AMD processors at this time and so if you are using server hardware with a Xeon processor it won't work.
