### ISSUE TITLE
Stuck on [EB|#LOG:EXITBS:START]

### ISSUE THREAD

**Issue by vicenterendo** [balopez83/macOS_On_Hyper-V#32]
After creating the VM, when booting UEFI:

![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/76400414/ddbc524f-204f-465a-99fd-8cc36efc2adf)

The boot process gets stuck on `[EB|#LOG:EXITBS:START]`

![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/76400414/fd162045-7ef6-4049-a764-5e30a71b5235)

Thanks in advance for any help!

EDIT: I am attempting to install macOS 13 Ventura

**Comment by balopez83** [comment]
@vicenterendo My guess is you are using an unsupported processor. What are your system specs? Also what specs have you provided the virtual machine?

**Comment by vicenterendo** [comment]
My host has an r5 5600x CPU, 32GB RAM and a B550 Plus Mobo
I set everything up as in [this guide](https://github.com/balopez83/macOS_On_Hyper-V/blob/main/1-QuickStart.md). Didn't think my host would be important, I'm new to this virtualization stuff.

**Comment by vicenterendo** [comment]
Oh, there it is
![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/76400414/fc6d1702-c4df-4120-8b6c-68642a87984d)

Sorry for wasting your time :(
