### ISSUE TITLE
12th Gen Intel(R) Core(TM) i7-1255U   1.70 GHz - failed to find a compatible processor

### ISSUE THREAD

**Issue by kornflex** [balopez83/macOS_On_Hyper-V#34]
Hello,

After install, I can't boot MacOS. 
 failed to find a compatible processor 
<img width="765" alt="image" src="https://github.com/balopez83/macOS_On_Hyper-V/assets/5457493/f3bcaee6-e062-4b3d-9f57-1480011c8c49">

I have a I7 processor.
I try to change the processor in config.plist, but still the same problem..

How can I fix this ?

Thank you

**Comment by balopez83** [comment]
@kornflex This isn't a processor issue. If it was then you wouldn't have been able to install. Also a processor issue only shows up at early boot [EB some error]. 

It's more likely that you missed a step in the configuration of Hyper-v or you changed something you shouldn't have in the config.plist. 

Did you allocate at least 8gb of ram. It's impossible to help more unless you can generate logs as the screenshot doesn't show what the kernel panicked on.

**Comment by kornflex** [comment]
you are correct, I put the original file and it's working !
I don't know why I doesn't work before :/ 

Yes, I had 8gb ram :/ 

Thank you for your help
