### ISSUE TITLE
Provide a ready-to-run package

### ISSUE THREAD

**Issue by thany** [balopez83/macOS_On_Hyper-V#35]
Hyper-V can import ready made VM packages, like virtual appliances one could say.

So instead of a 58000-point list on how to install macOS, why not simply provide a download to the result of those steps?

**Comment by balopez83** [comment]
@thany Because then I would get a take down request from Apple. 

Also GitHub has data limits and doesn't support individual files greater than 100mb and caps total transfers per month on free accounts.
