### ISSUE TITLE
Screen Resolution

### ISSUE THREAD

**Issue by AbhijitKhatua** [balopez83/macOS_On_Hyper-V#40]
I know the previous issue is marked closed but I'm opening  again bcz its not solved yet and I wanted to remind.

**Comment by balopez83** [comment]
@AbhijitKhatua It was closed because this is not something I can solve and it can only be solved by someone creating a driver for hyper-v or for the acidanthera team to create support with their kext. Either way it's outside the scope of this project and not being worked on.

**Comment by AbhijitKhatua** [comment]
😞, No problem thanks for the reply
