### ISSUE TITLE
How to change th display resolution?

### ISSUE THREAD

**Issue by edgean** [balopez83/macOS_On_Hyper-V#42]
thank you for the solution, it is perfect for run, but my VM`s display is 1024*768, and can not be changed. How could I change it to high resolution. thanks.

**Comment by balopez83** [comment]
@edgean Hi, as discussed in other closed issues this is not yet possible. macOS in Hyper-v is still in an alpha stage and no graphics driver has been developed that will force hyper-v into a larger resolution. If you need something with a higher resolution up will want to look at macOS in VMWare.
