### ISSUE TITLE
macOS Installer fails to launch

### ISSUE THREAD

**Issue by wengland02** [balopez83/macOS_On_Hyper-V#8]
The new version of the UEFI.vhdx allows me to get to the OpenCore menu but when I try to launch the installer, the installer stops at the point of the first screenshot. About a minute later, an error screen pops up as shown in the second screenshot. After 10 seconds, it returns to the OpenCore menu. Any solutions?

![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/95513176/6fc43937-da0c-45d0-ae52-a38be042c2c8)

![image](https://github.com/balopez83/macOS_On_Hyper-V/assets/95513176/3aa99019-a08e-4bb2-9b35-bf47ea8dd301)

**Comment by balopez83** [comment]
@wengland02 What macOS version installer are you trying to launch?

**Comment by wengland02** [comment]
@balopez83 I tried installing both Monterey and Ventura but the result is the same.

**Comment by balopez83** [comment]
@wengland02  So I updated the instructions to reflect this but I believe the issue is too little memory assigned to the virtual machine. I had to have a minimum of 6gb of memory assigned before I got a successful boot from the recovery installer. I would highly recommend 8gb as even 6gb was not very smooth. I believe Big Sur and later started requiring more memory in order to boot properly.

**Comment by balopez83** [comment]
@wengland02 When you try again with more memory you should still expect it to pause at that initial boot text and it might appear to be still frozen. Just be patient for a minute and it should start loading the kernel and scrolling the verbose text

**Comment by balopez83** [comment]
@wengland02 I should add that technically it can run on 4gb of ram assigned but it seems that the recovery/installer requires the full 8gb. I was able to boot Sonoma with just 4gb assigned but I cannot launch the installers with just 4gb. Not sure why it matters for an installer but that was my experience.

**Comment by balopez83** [comment]
@wengland02 please let me know if this was able to resolve your issue or if you are still encountering problems?

**Comment by wengland02** [comment]
@balopez83 Setting it 8GB worked. Thanks for the help. I will let you know if I come across any other issues.
